### ISSUE TITLE
Range Clip Config for filtering 

### ISSUE THREAD

**Issue by johnd2010** [ctu-mrs/mrs_octomap_mapping_planning#12]
Hi,
It seems that the config files (ros_packages/mrs_octomap_mapping_planning/tmux/simulation_example/config) in the tm reflect the range clipping as "range_clip" and not 
" clip:
    range:
      use: true
      min: 0.7  # [m]
      max: 40.0 # [m]"

**Comment by klaxalk** [comment]
You are right! I will fix that. Thanks!
